build.gradle
src/main/java/org/formflowstartertemplate/app/submission/actions/UpdateIncomeAmountsBeforeSaving.java
src/main/java/org/formflowstartertemplate/app/submission/actions/UpdatePersonalInfoDates.java
src/main/java/org/formflowstartertemplate/app/submission/actions/ValidateMovedToUSADate.java
src/main/java/org/formflowstartertemplate/app/submission/conditions/AllHouseholdMembersHaveIncome.java
src/main/java/org/formflowstartertemplate/app/submission/conditions/ExceedsIncomeThreshold.java
src/main/java/org/formflowstartertemplate/app/submission/conditions/HasHousehold.java
src/main/java/org/formflowstartertemplate/app/submission/conditions/HouseholdMemberAlreadyHasIncome.java
src/main/java/org/formflowstartertemplate/app/submission/conditions/IncomeSelectedSelf.java
src/main/resources/flows-config.yaml

- Lock in to library version `0.0.2-SNAPSHOT`
- We decided that `0.0.1-SNAPSHOT` will now the f[rozen version of the library](https://github.com/codeforamerica/form-flow/releases/tag/0.0.1-SNAPSHOT) for Doc LA to use for their research trip
- Now all future rolling changes to the library will be pushed to `0.0.2-SNAPSHOT`
- More info in our [pivotal tracker ticket](https://www.pivotaltracker.com/story/show/184730706) if you're curious
- Update condition/action paths

Update library version to new snapshot and fix conditions/actions

---

src/main/resources/messages.properties
src/main/resources/templates/error/404.html
src/main/resources/templates/error/500.html

It will be nice to know when there's an error due to server error vs a routing issue (page not found).
Apparently we can just do this by putting a file named "404.html" in the right place. I copied the 500 error page from the form-flow library and copied it for 404 as well (with updated strings I stole from GCF).

Add 404 page

---

.github/workflows/deploy.yaml
build.gradle

I'm unsure whether this will work with no further configuration, so this is a bit experimental. I believe this will read from the SENTRY_DSN environment variable (which I just added to Github).

Add sentry for error tracking

---

README.md
src/main/java/org/homeschoolpebt/app/config/SecurityConfiguration.java

There was a bug with the /navigation endpoint: it was navigating to http rather than keeping "https" before the URL.
Let's use this little configuration bean to pick up the X-Forwarded-{For,Proto,Port} headers and use them for URL generation.
ASANA-1204443722442392

Add ForwardedHeaderFilter to keep "https" as the scheme

---

build.gradle
src/main/java/org/homeschoolpebt/app/submission/conditions/IsJobHourly.java
src/main/java/org/homeschoolpebt/app/submission/conditions/PreScreenHasOnlyOneStudent.java
src/main/resources/flows-config.yaml
src/test/java/org/homeschoolpebt/app/journeys/PebtFlowJourneyTest.java

This is the first of some complicated page skipping logic in the income flow, enabled by https://github.com/codeforamerica/form-flow/pull/206.
* Upgrade FFL 0.0.3 -> 0.0.4 to get the change.
* Add condition to only show the "what's your hourly wage" page if you answer that the job is paid hourly.
* Update PreScreenHasOnlyOneStudent method signature since it's used in a subflow and must receive the `subflowUuid` now.
* Test via answering "Yes", then going back, changing to "No", and verifying that we end up on the right page either way.

Add Condition for "hourly wage" page

---

.github/workflows/run-tests.yaml

Switch to `gradle/gradle-build-action@v2` for Gradle cache, which only saves the cache when doing builds on `main`. This allows pull requests to save about 40 seconds per build, or about 15-20% of the build time.
Also: Change Docker image for Postgres in the hopes it download & starts faster.

Adjust Gradle config in GitHub Actions

---

src/main/resources/templates/fragments/icons.html

The FFL icons all have this. Presumably it's so that screen readers skip them. Let's add it to all of our icons as well.

Add aria-hidden="true" to our icons

---

build.gradle

This allows the app to launch in dev mode on my workstation. Error message was:
```
***************************
APPLICATION FAILED TO START
***************************
Description:
An attempt was made to call a method that does not exist. The attempt was made from the following location:
org.homeschoolpebt.app.submission.emails.MailGunEmailClient.<init>(MailGunEmailClient.java:29)
The following method did not exist:
'com.mailgun.api.MailgunApi com.mailgun.client.MailgunClient$MailgunClientBuilder.createApi(java.lang.Class)'
The calling method's class, org.homeschoolpebt.app.submission.emails.MailGunEmailClient, was loaded from the following location:
file:/Users/asheesh/projects/homeschool-pebt/build/classes/java/main/org/homeschoolpebt/app/submission/emails/MailGunEmailClient.class
The …
```

Remove Mailgun dependency in favor of form-flow depending on it

---

src/main/resources/application.yaml
src/test/java/org/homeschoolpebt/app/journeys/PebtFlowJourneyTest.java
src/test/java/org/homeschoolpebt/app/utils/AbstractBasePageTest.java
src/test/resources/application-test.yaml

It's been failing. This rewrites it to use Selenium waits rather than the awaitility library. This should tolerate the elements being a bit slower, since it won't raise if the element isn't present upon the first execution of the wait condition.

Rewrite uploadFile test helper to maybe be more reliable?

---

src/main/java/org/homeschoolpebt/app/StaticPageController.java
src/main/resources/application.yaml
src/main/resources/messages.properties
src/main/resources/templates/index.html
src/main/resources/templates/indexApplicationsDisabled.html

When setting DISABLE_APPLICATIONS=true, the "Apply now" buttons will be removed. This could give us a quick way to get the site deployed into production pre-launch.

Add feature flag to disable application buttons on homepage

---

build.gradle
src/main/resources/application.yaml

Database-backed sessions are necessary to persist user data across container restarts. This should be a nice change for dev as well as being necessary in demo/prod.
It seems like the spring-session-jdbc library manages the schema and everything.

Store sessions in the database

---

.github/workflows/deploy.yaml

* There's no way to link to the job that's running, apparently, only the current "run".
* Set RELEASE_HEALTHCHECK_TIMEOUT=240 since I just saw a deploy to demo that took 178 seconds for the app to start D:

Fix deploy slack message URL and wait longer for app to start

---

src/main/java/org/homeschoolpebt/app/submission/conditions/MissingAnyDocumentUploads.java
src/main/java/org/homeschoolpebt/app/submission/conditions/NeedsIncomeVerification.java
src/main/java/org/homeschoolpebt/app/utils/SubmissionUtilities.java
src/main/resources/flows-config.yaml
src/main/resources/messages.properties
src/main/resources/templates/pebt/addingDocuments.html
src/main/resources/templates/pebt/docPendingConfirmation.html
src/main/resources/templates/pebt/signpostIncome.html
src/main/resources/templates/pebt/uploadEnrollmentDocuments.html
src/main/resources/templates/pebt/uploadIdentityDocuments.html
src/main/resources/templates/pebt/uploadIncomeDocuments.html
src/main/resources/templates/pebt/uploadUnearnedIncomeDocuments.html
src/test/java/org/homeschoolpebt/app/data/TransmissionRepositoryServiceTest.java
src/test/java/org/homeschoolpebt/app/utils/AbstractBasePageTest.java
src/test/java/org/homeschoolpebt/app/utils/SubmissionUtilitiesTest.java

* Add "docPendingConfirmation" page to tell the user we need more docs from them.
* Create a utils method `getMissingDocUploads` which does the logic to determine whether any doctypes were needed and are missing.
* Redo the flows-config logic for the doc upload section to take the user to that page whenever they would have otherwise gone to the doc upload confirmation page.
* This necessitated flipping the return value of some of the other Condition's in order to get the `nextScreens` logic to fall back to the right page.
This logic is really complicated now! I wouldn't be surprised if I made a mistake. There is a subsequent story to write a journey test of some doc upload situations.

Allow skipping app doc upload screens

---

src/main/resources/application-demo.yaml
src/main/resources/application-production.yaml
src/main/resources/application.yaml
src/test/resources/application-test.yaml

* I don't think the demo config was doing anything since the datasource is clearly wrong (yet demo works). Also, the S3 bucket name is the same as in application.yaml, so why would that be necessary?
* This adds a production YAML, too, since we want to set `thymeleaf.cache` to true there.

Remove useless demo config and add production config

---

src/main/java/org/homeschoolpebt/app/data/TransmissionRepositoryService.java
src/main/java/org/homeschoolpebt/app/submission/actions/HandleApplicationSigned.java
src/main/java/org/homeschoolpebt/app/submission/actions/HandleLaterdocSubmitted.java
src/main/resources/templates/pebt/nextSteps.html
src/test/java/org/homeschoolpebt/app/data/TransmissionRepositoryServiceTest.java
src/test/java/org/homeschoolpebt/app/submission/actions/HandleApplicationSignedTest.java

If the applicant signs the app, goes back, and resubmits the signature page, we don't want their app to be transmitted twice. (And, they should only receive the first copy of the confirmation message.)
This commit updates the HandleApplicationSigned and HandleLaterdocSubmitted actions to do nothing if the transmission already exists.

Update after-submit actions to do nothing the second time

---

src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/templates/pebt/homeAddress.html

This link was going to go to a flow section that we deprioritized.

Remove "I don't have a mailing address" link

---

src/main/java/org/homeschoolpebt/app/data/SentMessage.java
src/main/java/org/homeschoolpebt/app/data/SentMessageRepository.java
src/main/java/org/homeschoolpebt/app/data/SentMessageRepositoryService.java
src/main/java/org/homeschoolpebt/app/submission/actions/HandleApplicationSigned.java
src/main/java/org/homeschoolpebt/app/submission/messages/ScheduledMessages.java
src/main/java/org/homeschoolpebt/app/submission/messages/TwilioSmsClient.java
src/main/resources/db/migration/V2023.06.27.15.00.55__Create_sent_messages.sql
src/test/java/org/homeschoolpebt/app/journeys/ApplyForSelfJourneyTest.java
src/test/java/org/homeschoolpebt/app/journeys/PebtFlowJourneyTest.java
src/test/java/org/homeschoolpebt/app/submission/actions/HandleApplicationSignedTest.java
src/test/resources/logback.xml

This creates a simple table that stores IDs for all the twilio and
mailgun messages, in case we need to go back and check them for some
reason.

Store twilio & mailgun messages in `sent_messages` table

---

src/main/resources/templates/pebt/studentsSchoolYear.html

Just a boring JS issue since we were accidentally putting the `<input>`s
for the follow-up items within the `question-with-follow-up__question`.
That means that whenever the user clicked on an `<input>` within the
follow-ups, it was triggering it to close and reopen, which defocused
the field.

Fix JS glitch preventing inputting affidavit number

---

src/main/java/org/homeschoolpebt/app/utils/SubmissionUtilities.java
src/main/resources/templates/pebt/householdList.html
src/test/java/org/homeschoolpebt/app/utils/SubmissionUtilitiesTest.java

This adds a method that I hope we can call in all the places we show "(that's you!)"
It returns a map because we can then use the keys as the form `label` and the values as the form `values`.
@sree-cfa If you like it, I can look into using it in "Don't show duplicate names during document uploader". I also need to manually test it still! I am sharing this now to get early feedback.

Add getSelectableStudents to SubmissionUtilities

---

src/main/java/org/homeschoolpebt/app/submission/conditions/IsRequiredToVerifyIncome.java
src/main/java/org/homeschoolpebt/app/submission/conditions/NeedsEarnedIncomeDocs.java
src/main/java/org/homeschoolpebt/app/utils/SubmissionUtilities.java
src/main/resources/flows-config.yaml
src/main/resources/templates/pebt/addingDocuments.html
src/main/resources/templates/pebt/docPendingConfirmation.html
src/test/java/org/homeschoolpebt/app/journeys/ApplyForSelfJourneyTest.java
src/test/java/org/homeschoolpebt/app/utils/SubmissionUtilitiesTest.java

This commit refactors the previous `needsIncomeVerification` method into
two different methods:
* `isRequiredToVerifyIncome` - this handles the logic to determine
whether *ALL* income verification can be skipped, and
* `needsEarnedIncomeDocuments` - this handles the logic to determine
whether the earned income doc upload section should be skipped, which
is false when the applicant is not required to verify income OR when
there are no jobs reported on the application.
A couple related changes:
* I updated the ApplyForSelfJourneyTest to test this condition.
* The names of the Conditions have been updated to match these methods.
More description in ASANA-1204918907154109.

Skip only *earned* income when there are no jobs

---

src/main/java/org/homeschoolpebt/app/utils/SubmissionUtilities.java
src/main/resources/templates/pebt/incomeChooseHouseholdMember.html
src/test/java/org/homeschoolpebt/app/journeys/ApplyForSelfJourneyTest.java
src/test/java/org/homeschoolpebt/app/utils/SubmissionUtilitiesTest.java

Remove duplicate name in income household list when applicant is in household and is not applying for self
see #236

Fix Duplicate name in income list

---

src/main/java/org/homeschoolpebt/app/utils/SubmissionUtilities.java
src/main/resources/templates/pebt/reviewPersonalInfo.html

* Fix bug where we were using `==` to compare strings (this will fix the
address used on the Applicant Summary PDF to match this logic).
* Create a new combinedAddressHtml method to format the address properly
for the reviewPersonalInfo page.
* Make a couple minor changes to the spacing on that page.

Use validated address (if selected) on "reviewPersonalInfo"

---

src/main/resources/messages.properties
src/main/resources/messages_es.properties
src/main/resources/templates/pebt/success.html

This is causing the `flow` attr on the `submission` to `docUpload` when we want it to remain `pebt`. This is problematic as we'll get bunch of `docUpload` submissions with extra data not from the doc upload flow, if the user does not nav back to the pebt flow (which will reset it back to `pebt`). Issue still remains on how these submissions get fragmented, but this hopefully should help 🤞

Remove docupload links from pebt flow

---

src/main/resources/logback-spring.xml

We expected to see MDC attributes in datadog after we added the logging filter. We think we also need to enable JSON Console to be able to see MDC. So we [copy/pasted the doc-la settings here](https://github.com/codeforamerica/la-doc-uploader/blob/main/src/main/resources/logback-spring.xml).

Add doc-la logback spring settings

---

src/main/java/org/homeschoolpebt/app/StaticPageController.java

Instead of setting it to null (which then will cause a new session for
any static asset being requested), let's reinitialize the session right
away.
Co-Authored-By: Sree Prasad <sprasad@codeforamerica.org>
Co-Authored-By: Cypress Borg <cborg@codeforamerica.org>
Co-Authored-By: Ana Medrano Fernandez <amedrano@codeforamerica.org>

Reset the SESSION cookie on the homepage

---

src/main/java/org/homeschoolpebt/app/cli/TransmitterCommands.java
src/main/java/org/homeschoolpebt/app/data/TransmissionRepository.java
src/test/java/org/homeschoolpebt/app/cli/TransmitterCommandsTest.java

Also:
- Store applicant summary as 00_applicant_summary.pdf for alphabetical ordering ease-of-use
- Convert messy characters / and : into _ to avoid path traversal or other oddities
- Sort user files deterministically to ensure filename ordering stays consistent
- Allow IOException to bubble up (was being squelched presumably because lambdas cannot throw)

Handle duplicate original filenames in Transmitter

---

.github/workflows/run-tests.yaml

This is recommended by the maintainer as a potential workaround around
network flakiness happening right now?
https://github.com/nanasess/setup-chromedriver/issues/199

Pin chromedriver version for now

---

src/main/java/org/homeschoolpebt/app/config/DataRequiredHandlerConfiguration.java
src/main/java/org/homeschoolpebt/app/submission/interceptors/DataRequiredInterceptor.java
src/test/java/org/homeschoolpebt/app/journeys/DataValidationJourneyTest.java

This implements a basic "redirect to homepage" functionality when we
detect the session has been split. We detect a split based on:
1. Before the "personalInfo" page, the absence of
"hasMoreThanOneStudent".
2. After the "personalInfo" page, the absence of the "firstName" field.
This logic is implemented in an Interceptor, which runs outside the
controllers. As such, it has to parse the URL the same way that the
controller would in order to determine which screen is shown. This is
pretty hacky and I'd prefer pretty much any other way.

Add redirect to homepage when missing data

---

src/main/resources/templates/fragments/analytics.html

This is a new field in an attempt to help me understand whether people
are opening new tabs, or what.
The idea is to use sessionStorage to create a tab-local variable that is
sent to Mixpanel. I tested this manually, and it does seem to generate a
new value when a new tab is opened.

Create a "pebtTabId" tab-local variable and send to Mixpanel

---

src/main/java/org/homeschoolpebt/app/filters/LoggingFilter.java

This changes the logic so that the HttpServletRequest doesn't accidentally create a session when [getSession](https://jakarta.ee/specifications/servlet/4.0/apidocs/javax/servlet/http/httpservletrequest#getSession--) is called. 
Replaces it with this [getSession](https://jakarta.ee/specifications/servlet/4.0/apidocs/javax/servlet/http/httpservletrequest#getSession-boolean-) call instead.

Revamps the log filter logic so it doesn't accidentally create a new session.

---

Dockerfile
crontab

The terminal transcript below shows that with the `-D` command in place, the app does not seem to crash when being launched with the `checkForUnsubmittedDocs` command.
```
asheesh@asheesh-cfa-2021-mbp homeschool-pebt % ./gradlew assemble
> Configure project :
📚Using form flow library 0.0.7.1
> Task :compileJava
/Users/asheesh/projects/homeschool-pebt/src/main/java/org/homeschoolpebt/app/config/SecurityConfiguration.java:17: warning: [removal] formLogin() in HttpSecurity has been deprecated and marked for removal
httpSecurity.formLogin().disable();
^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
BUILD SUCCESSFUL in 4s
7 actionable tasks: 7 executed
asheesh@asheesh-cfa-2021-mbp homeschool-pebt % cp …
```

In crontab, for shell commands, do not start web app

---

Procfile

Starting with the most recent deploy, we started getting this error:
```
/entrypoint.sh: exec: line 29: exec: not found
```

Remove "exec" from procfile command

---

src/main/java/org/homeschoolpebt/app/cli/AdHocMessenger.java
src/main/java/org/homeschoolpebt/app/data/SentMessageRepository.java
src/main/java/org/homeschoolpebt/app/data/SentMessageRepositoryService.java
src/main/java/org/homeschoolpebt/app/data/TransmissionRepository.java
src/main/java/org/homeschoolpebt/app/submission/messages/LastMinuteReminderMessage.java
src/main/java/org/homeschoolpebt/app/submission/messages/ScheduledMessages.java
src/test/java/org/homeschoolpebt/app/cli/AdHocMessengerTest.java

This message will go out to any unsubmitted submission that has an email
address provided (currently ~3200). To do that, most easily, we'll do
the set intersection in Java.
Since this runs the risk of error, we'll make this idempotent by
checking for a SentMessage record first before re-sending. So hopefully
if there's an error, we can re-run this.

Add ad-hoc LastMinuteReminderMessage
