codeforamerica/homeschool-pebt

- .git-authors
Add this file so we can git duet ✨
> Add git authors from GCF

- .github/workflows/deploy.yaml
- .github/workflows/run-tests.yaml
- build.gradle
- src/main/java/org/homeschoolpebt/app/submission/actions/SendConfirmationEmail.java
- src/main/java/org/homeschoolpebt/app/submission/conditions/AddressValidationIsOff.java
- src/main/java/org/homeschoolpebt/app/submission/emails/MailGunEmailClient.java
- src/main/resources/application.yaml
- src/main/resources/flows-config.yaml
- src/main/resources/templates/faq.html
- src/main/resources/templates/index.html
- src/main/resources/templates/privacy.html
- src/main/resources/templates/ubi/annualHouseholdIncome.html
- src/main/resources/templates/ubi/docSubmitConfirmation.html
- src/main/resources/templates/ubi/documentOffboarding.html
- src/main/resources/templates/ubi/documentRecommendations.html
- src/main/resources/templates/ubi/householdDeleteConfirmation.html
- src/main/resources/templates/ubi/householdList.html
- src/main/resources/templates/ubi/income.html
- src/main/resources/templates/ubi/incomeDeleteConfirmation.html
- src/main/resources/templates/ubi/signName.html
- src/test/java/org/homeschoolpebt/app/journeys/UbiFlowJourneyTest.java
- src/test/resources/application-test.yaml
* We still have to move it to the right place in the flow
> Add proof of concept for confirmation email

- .github/workflows/run-tests.yaml
- src/main/resources/application.yaml
- src/test/resources/application-test.yaml
* We used [this pull request]( https://github.com/codeforamerica/form-flow-starter-app/pull/111) to fix the bug with tests. This change moves from h2 to postgres when running tests.
* You will need to run the db creation script from the above pull request in the comments. It is the one labeled "created form-flow-test"
> Fix UUID bug when running journey tests.

- src/main/resources/messages.properties
- src/main/resources/templates/fragments/pebtIcons.html
- src/main/resources/templates/pebt/howThisWorks.html
Still need to add the PEBT icons from [Tom's recent commit](https://github.com/codeforamerica/homeschool-pebt/pull/11), and also styling at some point.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204323976571538
> Add copy and accordions to how this works screen

- src/test/java/org/homeschoolpebt/app/config/FlywayConfiguration.java
- src/test/resources/application-test.yaml
See https://github.com/codeforamerica/form-flow-starter-app/pull/123
> Add recent form-flow-starter-app changes

- src/main/resources/messages.properties
- src/main/resources/templates/pebt/hasIncome.html
- src/test/java/org/homeschoolpebt/app/journeys/PebtFlowJourneyTest.java
> Adjust hasIncome page for per-job income flow

- src/main/java/org/homeschoolpebt/app/utils/SubmissionUtilities.java
- src/main/resources/templates/fragments/footer.html
> Add footer links for summary PDF and editing transifex copy

- src/main/java/org/homeschoolpebt/app/inputs/Pebt.java
- src/main/java/org/homeschoolpebt/app/preparers/StudentsPreparer.java
- src/main/java/org/homeschoolpebt/app/utils/SubmissionUtilities.java
- src/main/resources/messages.properties
- src/main/resources/templates/pebt/studentsSchoolYear.html
- src/test/java/org/homeschoolpebt/app/preparers/IncomePreparerTest.java
- src/test/java/org/homeschoolpebt/app/preparers/JobsPreparerTest.java
- src/test/java/org/homeschoolpebt/app/preparers/StudentsPreparerTest.java
- src/test/java/org/homeschoolpebt/app/utils/SubmissionUtilitiesTest.java
Doing it as a plain text input to begin with. We can change it to being
a combobox later.
ASANA-1204692695351412
> Add question for virtual school name (and fill PDF)

- src/test/java/org/homeschoolpebt/app/utils/SeleniumFactory.java
When the button we're trying to click is on the bottom edge of the browser, selenium doesn't actually click it. If we just make the browser bigger every time, there will never be an issue :D.
> Fix test failure by making browser even TALLER

- src/main/java/org/homeschoolpebt/app/preparers/AssistanceProgramsPreparer.java
- src/main/java/org/homeschoolpebt/app/preparers/ContactInfoPreparer.java
- src/main/java/org/homeschoolpebt/app/preparers/IncomePreparer.java
- src/main/java/org/homeschoolpebt/app/preparers/JobsPreparer.java
- src/main/java/org/homeschoolpebt/app/preparers/StudentsPreparer.java
- src/test/java/org/homeschoolpebt/app/preparers/AssistanceProgramsPreparerTest.java
- src/test/java/org/homeschoolpebt/app/preparers/ContactInfoPreparerTest.java
- src/test/java/org/homeschoolpebt/app/preparers/IncomePreparerTest.java
- src/test/java/org/homeschoolpebt/app/preparers/JobsPreparerTest.java
- src/test/java/org/homeschoolpebt/app/preparers/StudentsPreparerTest.java
Once this [library PR goes into main](https://github.com/codeforamerica/form-flow/pull/233), this PR handles the breaking change update to preparer parameters.
> Remove data from preparers

- src/main/java/org/homeschoolpebt/app/submission/actions/UpdateStudentBirthday.java
We have an upcoming PR that deprecates an Action. This will resolve that deprecation, when you see it. 
https://github.com/codeforamerica/form-flow/pull/245
> Updates code onPost action changes

- .github/workflows/deploy.yaml
- Dockerfile
This is untested, but I think this should allow us to deploy to production via triggering the Github action.
> Add config to deploy to production :shipit:

- .github/workflows/deploy.yaml
- src/main/resources/application.yaml
And put the environment name of the deploy in the github action name
> Add `production` config to application.yaml

- src/test/resources/browser-selenium.side
* Better names
* Fix CalFresh field
> Update selenium IDE file

- .github/workflows/deploy.yaml
8th time's the charm?
* Don't hardcode the app name
* Use short rev in the URL for sanity's sake.
> Attempt to fix Slack deploy message (attempt 8)

- .github/workflows/deploy.yaml
Finally I think this will be it.
> Attempt to fix Slack deploy message (attempt 9)

- .github/workflows/deploy.yaml
This is Aptible Magic :sparkles:.
> Set FORCE_SSL=true in demo and production

- .github/workflows/deploy.yaml
* Add the URL to the current run.
* Switch to the OAuth method so the previous message can be edited.
> Attempt to fix Slack deploy message (attempt 10)

- build.gradle
- src/main/resources/templates/fragments/head.html
- src/main/resources/templates/fragments/inputs/combobox.html
- src/test/java/org/homeschoolpebt/app/journeys/PebtFlowJourneyTest.java
- src/test/java/org/homeschoolpebt/app/utils/AbstractBasePageTest.java
- src/test/java/org/homeschoolpebt/app/utils/Page.java
This is not ideal from a perf standpoint, but since it's hard to change the file uploading JavaScript from the FFL, we're kinda stuck with it.
> Fix JS race conditions by loading JS synchronously

- build.gradle
- src/main/resources/application-demo.yaml
- src/main/resources/application.yaml
- src/test/resources/application-test.yaml
This copies the config from LA Doc Uploader, which apparently works.
* Use sentry-spring-boot-starter-jakarta instead of the one without jakarta.
* Set a couple more config values
> Try again to enable Sentry

- src/main/java/org/homeschoolpebt/app/StaticPageController.java
> Add redirect from /docs -> start of laterdocs flow

- src/main/resources/flows-config.yaml
- src/test/java/org/homeschoolpebt/app/journeys/PebtFlowJourneyTest.java
It's vestigial from the starter app.
> Remove "economicHardship" page

- src/main/java/org/homeschoolpebt/app/inputs/DocUpload.java
- src/main/resources/messages.properties
- Make laterdocs application number required
> make laterdocs app number required

- src/main/java/org/homeschoolpebt/app/inputs/DocUpload.java
- src/main/java/org/homeschoolpebt/app/inputs/Pebt.java
- src/main/resources/templates/index.html
- src/main/resources/templates/pebt/incomeRegularPayCalculator.html
- src/main/resources/templates/pebt/studentsSchoolYear.html
- Fix thymeleaf unwrapped fragment warnings
- Fix lombok `EqualsAndHashCode` warning
> Fix thymeleaf and lombok warnings

- .github/workflows/deploy.yaml
- Update Github deploy action to skip duplicate deploys
- Fix syntax of deploy YAML
> Fix syntax of deploy YAML

- src/main/java/org/homeschoolpebt/app/submission/messages/ConfirmationMessage.java
- src/main/java/org/homeschoolpebt/app/submission/messages/DocReminderMessage.java
- src/main/java/org/homeschoolpebt/app/utils/SubmissionUtilities.java
translations here: https://docs.google.com/document/d/1KNjKF-LKcgc0FcYDXGiXN5SJSoMz_fVYD1yuQwMtY4Y/edit
> Add logic for messages to detect Spanish

- crontab
- src/main/java/org/homeschoolpebt/app/cli/TransmitterCommands.java
- src/main/java/org/homeschoolpebt/app/data/TransmissionRepository.java
- src/test/java/org/homeschoolpebt/app/cli/TransmitterCommandsTest.java
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204463114413092
> Updating file transfer for later docs

- src/main/java/org/homeschoolpebt/app/inputs/Pebt.java
- src/main/resources/messages.properties
> Adding not-blank validation for phone

- src/main/resources/messages.properties
- src/main/resources/static/assets/css/custom.css
- src/main/resources/templates/fragments/footer.html
- src/main/resources/templates/index.html
- src/test/java/org/homeschoolpebt/app/journeys/ApplyForSelfJourneyTest.java
- src/test/java/org/homeschoolpebt/app/journeys/LaterDocsJourneyTest.java
- src/test/java/org/homeschoolpebt/app/journeys/PebtFlowJourneyTest.java
- src/test/java/org/homeschoolpebt/app/journeys/PreScreenJourneyTest.java
- src/test/java/org/homeschoolpebt/app/journeys/StaticPagesJourneyTest.java
Lots of icons were missing from honeycrisp.
> Implement homepage v2.6

- src/main/resources/templates/pebt/studentsWouldAttendSchoolName.html
> Allow skipping "would attend school" page

- src/main/java/org/homeschoolpebt/app/utils/SubmissionUtilities.java
- src/main/resources/templates/pebt/householdList.html
- src/main/resources/templates/pebt/uploadIdentityDocuments.html
- src/test/java/org/homeschoolpebt/app/utils/SubmissionUtilitiesTest.java
> If student is applying for themselves, hide applicant name on doc uploader

- src/main/java/org/homeschoolpebt/app/inputs/Pebt.java
- src/main/java/org/homeschoolpebt/app/submission/conditions/AbstractPebtCondition.java
- src/main/java/org/homeschoolpebt/app/submission/conditions/IsJobHourly.java
- src/main/java/org/homeschoolpebt/app/submission/conditions/IsJobPaidYearly.java
- src/main/java/org/homeschoolpebt/app/submission/conditions/IsJobSelfEmployed.java
- src/main/java/org/homeschoolpebt/app/submission/conditions/IsStudentTKto2.java
- src/main/java/org/homeschoolpebt/app/submission/conditions/PreScreenNotTK2.java
- src/main/resources/flows-config.yaml
- src/main/resources/messages.properties
- src/main/resources/templates/pebt/preScreenTKto2.html
- src/test/java/org/homeschoolpebt/app/journeys/PebtFlowJourneyTest.java
- src/test/java/org/homeschoolpebt/app/journeys/PreScreenJourneyTest.java
- Add "preScreenTKto2" screen
- Skip "studentsUnenrolledSchoolName" if TK-2
> Ask for TK-2 in prescreen

- src/main/java/org/homeschoolpebt/app/utils/SubmissionUtilities.java
- src/test/java/org/homeschoolpebt/app/utils/SubmissionUtilitiesTest.java
They will be included in the "student" subflow
> Basic Info applicant should not be shown if they are applying for self

- src/main/resources/flows-config.yaml
- src/test/java/org/homeschoolpebt/app/journeys/ApplyForChildOfSingleParentJourneyTest.java
> Show household benefits question when skipping income flow

- .github/workflows/deploy.yaml
- src/main/resources/application.yaml
- src/main/resources/templates/docUpload/docUploadSuccess.html
- src/main/resources/templates/fragments/analytics.html
- src/main/resources/templates/fragments/head.html
- src/main/resources/templates/pebt/success.html
* Track pageview on every page. This is basic but is better than
nothing.
> Add Mixpanel JS

- crontab
- src/main/java/org/homeschoolpebt/app/cli/TransmitterCommands.java
- src/main/java/org/homeschoolpebt/app/submission/messages/ScheduledMessages.java
Follow-up:
- Add more logging
- Check if removing chronjob actually stops job
Co-authored-by: Martha Pidcock <mpidcock@codeforamerica.org>
> Temporarily remove messaging job and add logs

- build.gradle
This hotfix was made for us, let's use it.
> Upgrade FFL 0.0.7 -> 0.0.7.1

- src/main/java/org/homeschoolpebt/app/filters/LoggingFilter.java
This configures the LoggingFilter to get the "id" attribute from the
session and add it to the log metadata blob.
> Add submissionId to JSON logs

- .github/workflows/run-tests.yaml
- src/main/java/org/homeschoolpebt/app/filters/LoggingFilter.java
- Fix spelling error in chromedriver-version test config
- Add two more fields to the logging config
> two small changes

- crontab
Co-authored-by: Asheesh Laroia <alaroia@codeforamerica.org>
> Run transmitter repeatedly while we're testing it

- src/main/resources/db/migration/V2023.08.08.11.08.11__Add_merged_submission_id_column.sql
This column will be populated by our manual data reconciliation scripts.
> Add merged_into_submission_id column

- src/main/java/org/homeschoolpebt/app/preparers/StudentsPreparer.java
- src/main/java/org/homeschoolpebt/app/utils/IncomeCalculator.java
- src/test/java/org/homeschoolpebt/app/preparers/IncomePreparerTest.java
- src/test/java/org/homeschoolpebt/app/preparers/StudentsPreparerTest.java
- src/test/java/org/homeschoolpebt/app/utils/SubmissionUtilitiesTest.java
- Fix NPE in StudentsPreparer with no anticipated school
- Fix IncomeCalculator NPE by only summing *complete* income entries
> Fix 2 NPEs in Student and Income preparers

- src/main/java/org/homeschoolpebt/app/interceptor/DataRequiredInterceptor.java
Co-authored-by: Arin Choi <achoi@codeforamerica.org>
> Prevent split-flow in laterdocs also

- src/main/resources/messages_es.properties
Why hath thy Github integration broken?
> Update homepage copy from transifex

- src/main/java/org/homeschoolpebt/app/config/DisabledApplicationsConfiguration.java
- src/main/java/org/homeschoolpebt/app/interceptor/DisabledApplicationsInterceptor.java
The time has come to block all access to these pages.
> Disable all /flow/pebt/ URLs when DISABLE_APPLICATIONS is set
